# Generated by Django 6.1.1 on 2026-09-30 10:02

import apps.library.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[apps.library.models.validators.member_age_validator]),
        ),
    ]
